### ISSUE TITLE
(Session One) The skelexor exercice binary should be rebuild

### ISSUE THREAD

**Issue by Menshin** [wrongbaud/hackaday-u#13]
The `skele` binary have remnants of debugging code outputting at which character the key and inputted password mismatchs (and the expected character key) :

![image](https://user-images.githubusercontent.com/7117411/126154203-74481c60-1f8a-44c4-b020-ab8298f887c0.png)

![image](https://user-images.githubusercontent.com/7117411/126154273-58b572c0-eeb3-453b-98a7-fb298cae1b96.png)

The binary should be rebuild from the corresponding [source](http://github.com/wrongbaud/hackaday-u/blob/master/session-one/exercises/source/skelexor.c) that is properly stripped of the debug code.

In the same vein, i'm not sure the updated build of https://github.com/wrongbaud/hackaday-u/pull/7 has been uploaded too.

Once again, thanks for this course (and those sessions 5->8 seems promising too !).

**Comment by wrongbaud** [comment]
This has been resolved with @dogacans most recent pull request, thanks!
