### ISSUE TITLE
Session 1 presentation - comments and typos

### ISSUE THREAD

**Issue by raenye** [wrongbaud/hackaday-u#2]
An amazing course!

Anyway, in `session-one/slides/session-1.pdf`, 
- Slide 20: "instruction is process**ed**".
- Slide 23: why `AH` instead of `AL` for 8 bit? after all, `EAX` is _lower_ half of `RAX`, `AX` is _lower_ half of `EAX` and `AH` is _upper_ half of `AX`.
- Slide 28: perhaps prepend the bullet by "And: " (like done in slide 27 with "Add: " and "Sub: "). Also, the example "and rax, rax" makes little sense.
- Slide 32: `RIP` instead of `EIP` since we're talking 64-bit.
- Slide 32: `CALL` pushes `RSP`, not `RBP`.
- Slide 33: why write immediate as `#5` instead of just `5`, as done on other slides?

**Comment by wrongbaud** [comment]
Hi @raenye !

Thank you for submitting these - this is excellent! I have attempted to answer your questions below and have updated the slides with this [commit](https://github.com/wrongbaud/hackaday-u/commit/c8295875e9956a5c86d9bf257b37359e89c85f7e)


> * Slide 20: "instruction is process**ed**". 

Fixed - there are lots of slides and sometimes things slip through the cracks!


> * Slide 23: why `AH` instead of `AL` for 8 bit? after all, `EAX` is _lower_ half of `RAX`, `AX` is _lower_ half of `EAX` and `AH` is _upper_ half of `AX`
. 
The purpose of this table was just to show that it can be accessed as a 8 bit register, but perhaps that doesn't come through properly without the soundtrack so I will add both representations!

> * Slide 28: perhaps prepend the bullet by "And: " (like done in slide 27 with "Add: " and "Sub: "). Also, the example "and rax, rax" makes little sense.

Done - I've updated the slides to have two registers being AND'ed 

> * Slide 32: `RIP` instead of `EIP` since we're talking 64-bit.

Updated - hopefully the new version makes more sense

> * Slide 32: `CALL` pushes `RSP`, not `RBP`.

Fixed! These slides were mixed in heavily with the calling convention slides earlier and this must have been a copy/paste error, good catch!

> * Slide 33: why write immediate as `#5` instead of just `5`, as done on other slides?

I think I had pulled that instruction from some assembly code that was written for the course, hence the ```#``` it's now been removed to reduce any confusion!

I'm closing this for now, but please re-open if you have any more questions or issues!
