### ISSUE TITLE
[Unrelated] Do you know of a gdb plugin for ghidra that can debug 3ds?

### ISSUE THREAD

**Issue by SirEnder125** [wrongbaud/hackaday-u#4]
Hey. Sorry for making this unrelated, but I saw your gba debugging thing and wondered if
you knew how to debug a 3ds with ghidra and luma3ds? I totally understand if this is the
wrong place to ask this.

**Comment by wrongbaud** [comment]
Hi, I am not aware of how exactly to debug luma3ds but I believe that they have enabled a GDB stub. You can use that with Ghidra debugger branch, or you can use standard GDB. Best of luck!

**Comment by SirEnder125** [comment]
I've tried Ghidra. It seems to work. That is, it freezes my game, just as GDB does before I type "continue".
But it never lets me continue. It never says it connected either.
