### ISSUE TITLE
simple-examples folder missing

### ISSUE THREAD

**Issue by bubbasnmp** [wrongbaud/hackaday-u#6]
https://github.com/wrongbaud/hackaday-u/blob/master/README.md
mentions "simple-examples":

* ```simple-examples```: This folder contains simple C programs used to outline certain x86_64 concepts
  

Is the folder missing or is this a formatting error for the README file?

**Comment by wrongbaud** [comment]
This is something that was leftover from an initial run of the course, these examples were not used. I'll remove it from the README, good catch!
